/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const ErrorPriority = {
  Undefined: 'Undefined',
  Critical: 'Critical',
  High: 'High',
  Low: 'Low',
  Fixed: 'Fixed',
} as const;

export type ErrorPriority = (typeof ErrorPriority)[keyof typeof ErrorPriority];

export const SubscriptionTier = {
  Free: 'Free',
  Starter: 'Starter',
} as const;

export type SubscriptionTier = (typeof SubscriptionTier)[keyof typeof SubscriptionTier];
