import { Response } from 'express';
import { contextProvider, contextSetter } from './contextHandler';
import { prisma } from '../../database/prismaClient';
import { Message } from '../../types/ai.types';

/**
 * Streams a model response based on the given prompt and context, while
 * saving the conversation and chat info into the database.
 *
 * @param {Response} res - Express response object.
 * @param {string} prompt - The user prompt.
 * @param {number} userID - ID of the user.
 * @param {string} apikey - API key for authentication.
 * @param {string} chatID - Unique chat identifier.
 * @param {string} conversationID - Unique conversation identifier.
 *
 * @returns {Promise<string>} - The full response generated by the model.
 */
export const streamModel = async (
  res: Response,
  prompt: string,
  userID: number,
  apikey: string,
  chatID: string,
  conversationID: string
): Promise<string> => {
  const model = "google/gemini-2.0-flash-lite-preview-02-05:free";

  // --- Input validation ---
  if (!prompt || typeof prompt !== "string") throw new Error("Valid prompt is required");
  if (!userID || typeof userID !== "number") throw new Error("Valid userID is required");
  if (!apikey || typeof apikey !== "string") throw new Error("Valid apikey is required");
  if (!chatID || typeof chatID !== "string") throw new Error("Valid chatID is required");
  if (!conversationID || typeof conversationID !== "string") throw new Error("Valid conversationID is required");

  // --- Fetch conversation context ---
  const context = await contextProvider(userID, chatID);

  // Prepare system message content
  const systemContent = context
    ? `You are an AI assistant. Use the following context to maintain a natural, continuous flow: ${context}. Do not greet me in every response. Avoid phrases like "from the context you provided"—your responses should feel seamless and conversational.`
    : "You are an AI assistant helping a developer fix issues in their application. Be concise and practical.";

  // --- API call to openrouter.ai ---
  const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apikey}`,
      "Content-Type": "application/json",
      "HTTP-Referer": "https://beepitt.com", // Optional, for OpenRouter rankings
      "X-Title": "Beepitt", // Optional
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: "system", content: systemContent },
        { role: "user", content: prompt },
      ],
      stream: true,
      max_tokens: 1000,
    }),
  });

  if (!response.body) {
    throw new Error("Response body is null");
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let finalResponse = "";

  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      const chunk = decoder.decode(value, { stream: true });
      const lines = chunk.split("\n");

      for (const line of lines) {
        if (line.startsWith("data: ")) {
          const data = line.slice(6).trim();
          if (data === "[DONE]") continue;

          try {
            const parsed = JSON.parse(data);
            const content = parsed.choices[0]?.delta?.content || "";
            if (content) {
              finalResponse += content;
              res.write(content);
            }
          } catch (e) {
            // Ignore parse errors for partial chunks
          }
        }
      }
    }

    // --- Persist chat and conversation to database ---
    try {
      await prisma.chat.upsert({
        where: { chatUUID: chatID },
        update: { updatedAt: new Date() },
        create: { chatUUID: chatID, chatName: prompt.slice(0, 50), userID },
      });

      await prisma.conversation.upsert({
        where: { conversationID },
        update: { response: finalResponse },
        create: {
          conversationID,
          chatID,
          userID,
          prompt,
          response: finalResponse,
        },
      });

      const conversation: Message = { prompt, response: finalResponse };
      await contextSetter(userID, context, conversation, chatID);
    } catch (error) {
      console.error("Failed to save conversation:", error);
    }

    res.end();
    return finalResponse;
  } catch (error) {
    console.error("Error while streaming model response:", error);
    res.write("\n[ERROR]: Failed to stream response from AI.");
    res.end();
    throw error;
  }
};
