/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * Please import the `PrismaClient` class from the `client.ts` file instead.
 */

import * as runtime from '@prisma/client/runtime/client';
import type * as Prisma from './prismaNamespace.js';

const config: runtime.GetPrismaClientConfig = {
  previewFeatures: [],
  clientVersion: '7.2.0',
  engineVersion: '0c8ef2ce45c83248ab3df073180d5eda9e8be7a3',
  activeProvider: 'postgresql',
  inlineSchema:
    '// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\n// Looking for ways to speed up your queries, or scale easily with your serverless or edge functions?\n// Try Prisma Accelerate: https://pris.ly/cli/accelerate-init\n\ngenerator client {\n  provider = "prisma-client"\n  output   = "../generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n\nenum ErrorPriority {\n  Undefined\n  Critical\n  High\n  Low\n  Fixed\n}\n\nenum SubscriptionTier {\n  Free\n  Starter\n}\n\nmodel User {\n  id                Int              @id @default(autoincrement())\n  otpVerified       Boolean          @default(false)\n  identifierKey     String           @unique\n  username          String           @unique\n  firstName         String?\n  lastName          String?\n  email             String           @unique\n  password          String\n  city              String?\n  timezone          String?\n  dateAndFormat     String?\n  createAt          DateTime         @default(now())\n  updateAt          DateTime         @updatedAt\n  subscription_tier SubscriptionTier\n  errors            Errors[]\n  contactDetails    ContactDetails[]\n}\n\nmodel Errors {\n  id                      Int            @id @default(autoincrement())\n  errorName               String\n  errorDesc               String\n  errorPriority           ErrorPriority?\n  errorDateAndTime        DateTime       @default(now())\n  errorResolveDateAndTime DateTime?\n  userId                  Int\n  user                    User           @relation(fields: [userId], references: [id])\n}\n\nmodel ContactDetails {\n  id              Int      @id @default(autoincrement())\n  telegramChatIds String[]\n  discordChatIds  String[]\n  userId          Int      @unique\n  user            User     @relation(fields: [userId], references: [id])\n}\n',
  runtimeDataModel: {
    models: {},
    enums: {},
    types: {},
  },
};

config.runtimeDataModel = JSON.parse(
  '{"models":{"User":{"fields":[{"name":"id","kind":"scalar","type":"Int"},{"name":"otpVerified","kind":"scalar","type":"Boolean"},{"name":"identifierKey","kind":"scalar","type":"String"},{"name":"username","kind":"scalar","type":"String"},{"name":"firstName","kind":"scalar","type":"String"},{"name":"lastName","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"city","kind":"scalar","type":"String"},{"name":"timezone","kind":"scalar","type":"String"},{"name":"dateAndFormat","kind":"scalar","type":"String"},{"name":"createAt","kind":"scalar","type":"DateTime"},{"name":"updateAt","kind":"scalar","type":"DateTime"},{"name":"subscription_tier","kind":"enum","type":"SubscriptionTier"},{"name":"errors","kind":"object","type":"Errors","relationName":"ErrorsToUser"},{"name":"contactDetails","kind":"object","type":"ContactDetails","relationName":"ContactDetailsToUser"}],"dbName":null},"Errors":{"fields":[{"name":"id","kind":"scalar","type":"Int"},{"name":"errorName","kind":"scalar","type":"String"},{"name":"errorDesc","kind":"scalar","type":"String"},{"name":"errorPriority","kind":"enum","type":"ErrorPriority"},{"name":"errorDateAndTime","kind":"scalar","type":"DateTime"},{"name":"errorResolveDateAndTime","kind":"scalar","type":"DateTime"},{"name":"userId","kind":"scalar","type":"Int"},{"name":"user","kind":"object","type":"User","relationName":"ErrorsToUser"}],"dbName":null},"ContactDetails":{"fields":[{"name":"id","kind":"scalar","type":"Int"},{"name":"telegramChatIds","kind":"scalar","type":"String"},{"name":"discordChatIds","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"Int"},{"name":"user","kind":"object","type":"User","relationName":"ContactDetailsToUser"}],"dbName":null}},"enums":{},"types":{}}',
);

async function decodeBase64AsWasm(wasmBase64: string): Promise<WebAssembly.Module> {
  const { Buffer } = await import('node:buffer');
  const wasmArray = Buffer.from(wasmBase64, 'base64');
  return new WebAssembly.Module(wasmArray);
}

config.compilerWasm = {
  getRuntime: async () => await import('@prisma/client/runtime/query_compiler_bg.postgresql.mjs'),

  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import('@prisma/client/runtime/query_compiler_bg.postgresql.wasm-base64.mjs');
    return await decodeBase64AsWasm(wasm);
  },
};

export type LogOptions<ClientOptions extends Prisma.PrismaClientOptions> = 'log' extends keyof ClientOptions
  ? ClientOptions['log'] extends Array<Prisma.LogLevel | Prisma.LogDefinition>
    ? Prisma.GetEvents<ClientOptions['log']>
    : never
  : never;

export interface PrismaClientConstructor {
  /**
   * ## Prisma Client
   *
   * Type-safe database client for TypeScript
   * @example
   * ```
   * const prisma = new PrismaClient()
   * // Fetch zero or more Users
   * const users = await prisma.user.findMany()
   * ```
   *
   * Read more in our [docs](https://pris.ly/d/client).
   */

  new <
    Options extends Prisma.PrismaClientOptions = Prisma.PrismaClientOptions,
    LogOpts extends LogOptions<Options> = LogOptions<Options>,
    OmitOpts extends Prisma.PrismaClientOptions['omit'] = Options extends {
      omit: infer U;
    }
      ? U
      : Prisma.PrismaClientOptions['omit'],
    ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  >(
    options: Prisma.Subset<Options, Prisma.PrismaClientOptions>,
  ): PrismaClient<LogOpts, OmitOpts, ExtArgs>;
}

/**
 * ## Prisma Client
 *
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Users
 * const users = await prisma.user.findMany()
 * ```
 *
 * Read more in our [docs](https://pris.ly/d/client).
 */

export interface PrismaClient<
  in LogOpts extends Prisma.LogLevel = never,
  in out OmitOpts extends Prisma.PrismaClientOptions['omit'] = undefined,
  in out ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['other'] };

  $on<V extends LogOpts>(
    eventType: V,
    callback: (event: V extends 'query' ? Prisma.QueryEvent : Prisma.LogEvent) => void,
  ): PrismaClient;

  /**
   * Connect with the database
   */
  $connect(): runtime.Types.Utils.JsPromise<void>;

  /**
   * Disconnect from the database
   */
  $disconnect(): runtime.Types.Utils.JsPromise<void>;

  /**
   * Executes a prepared raw query and returns the number of affected rows.
   * @example
   * ```
   * const result = await prisma.$executeRaw`UPDATE User SET cool = ${true} WHERE email = ${'user@email.com'};`
   * ```
   *
   * Read more in our [docs](https://pris.ly/d/raw-queries).
   */
  $executeRaw<T = unknown>(query: TemplateStringsArray | Prisma.Sql, ...values: any[]): Prisma.PrismaPromise<number>;

  /**
   * Executes a raw query and returns the number of affected rows.
   * Susceptible to SQL injections, see documentation.
   * @example
   * ```
   * const result = await prisma.$executeRawUnsafe('UPDATE User SET cool = $1 WHERE email = $2 ;', true, 'user@email.com')
   * ```
   *
   * Read more in our [docs](https://pris.ly/d/raw-queries).
   */
  $executeRawUnsafe<T = unknown>(query: string, ...values: any[]): Prisma.PrismaPromise<number>;

  /**
   * Performs a prepared raw query and returns the `SELECT` data.
   * @example
   * ```
   * const result = await prisma.$queryRaw`SELECT * FROM User WHERE id = ${1} OR email = ${'user@email.com'};`
   * ```
   *
   * Read more in our [docs](https://pris.ly/d/raw-queries).
   */
  $queryRaw<T = unknown>(query: TemplateStringsArray | Prisma.Sql, ...values: any[]): Prisma.PrismaPromise<T>;

  /**
   * Performs a raw query and returns the `SELECT` data.
   * Susceptible to SQL injections, see documentation.
   * @example
   * ```
   * const result = await prisma.$queryRawUnsafe('SELECT * FROM User WHERE id = $1 OR email = $2;', 1, 'user@email.com')
   * ```
   *
   * Read more in our [docs](https://pris.ly/d/raw-queries).
   */
  $queryRawUnsafe<T = unknown>(query: string, ...values: any[]): Prisma.PrismaPromise<T>;

  /**
   * Allows the running of a sequence of read/write operations that are guaranteed to either succeed or fail as a whole.
   * @example
   * ```
   * const [george, bob, alice] = await prisma.$transaction([
   *   prisma.user.create({ data: { name: 'George' } }),
   *   prisma.user.create({ data: { name: 'Bob' } }),
   *   prisma.user.create({ data: { name: 'Alice' } }),
   * ])
   * ```
   *
   * Read more in our [docs](https://www.prisma.io/docs/concepts/components/prisma-client/transactions).
   */
  $transaction<P extends Prisma.PrismaPromise<any>[]>(
    arg: [...P],
    options?: { isolationLevel?: Prisma.TransactionIsolationLevel },
  ): runtime.Types.Utils.JsPromise<runtime.Types.Utils.UnwrapTuple<P>>;

  $transaction<R>(
    fn: (prisma: Omit<PrismaClient, runtime.ITXClientDenyList>) => runtime.Types.Utils.JsPromise<R>,
    options?: {
      maxWait?: number;
      timeout?: number;
      isolationLevel?: Prisma.TransactionIsolationLevel;
    },
  ): runtime.Types.Utils.JsPromise<R>;

  $extends: runtime.Types.Extensions.ExtendsHook<
    'extends',
    Prisma.TypeMapCb<OmitOpts>,
    ExtArgs,
    runtime.Types.Utils.Call<
      Prisma.TypeMapCb<OmitOpts>,
      {
        extArgs: ExtArgs;
      }
    >
  >;

  /**
   * `prisma.user`: Exposes CRUD operations for the **User** model.
   * Example usage:
   * ```ts
   * // Fetch zero or more Users
   * const users = await prisma.user.findMany()
   * ```
   */
  get user(): Prisma.UserDelegate<ExtArgs, { omit: OmitOpts }>;

  /**
   * `prisma.errors`: Exposes CRUD operations for the **Errors** model.
   * Example usage:
   * ```ts
   * // Fetch zero or more Errors
   * const errors = await prisma.errors.findMany()
   * ```
   */
  get errors(): Prisma.ErrorsDelegate<ExtArgs, { omit: OmitOpts }>;

  /**
   * `prisma.contactDetails`: Exposes CRUD operations for the **ContactDetails** model.
   * Example usage:
   * ```ts
   * // Fetch zero or more ContactDetails
   * const contactDetails = await prisma.contactDetails.findMany()
   * ```
   */
  get contactDetails(): Prisma.ContactDetailsDelegate<ExtArgs, { omit: OmitOpts }>;
}

export function getPrismaClientClass(): PrismaClientConstructor {
  return runtime.getPrismaClient(config) as unknown as PrismaClientConstructor;
}
