/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `ContactDetails` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client';
import type * as $Enums from '../enums.js';
import type * as Prisma from '../internal/prismaNamespace.js';

/**
 * Model ContactDetails
 *
 */
export type ContactDetailsModel = runtime.Types.Result.DefaultSelection<Prisma.$ContactDetailsPayload>;

export type AggregateContactDetails = {
  _count: ContactDetailsCountAggregateOutputType | null;
  _avg: ContactDetailsAvgAggregateOutputType | null;
  _sum: ContactDetailsSumAggregateOutputType | null;
  _min: ContactDetailsMinAggregateOutputType | null;
  _max: ContactDetailsMaxAggregateOutputType | null;
};

export type ContactDetailsAvgAggregateOutputType = {
  id: number | null;
  userId: number | null;
};

export type ContactDetailsSumAggregateOutputType = {
  id: number | null;
  userId: number | null;
};

export type ContactDetailsMinAggregateOutputType = {
  id: number | null;
  userId: number | null;
};

export type ContactDetailsMaxAggregateOutputType = {
  id: number | null;
  userId: number | null;
};

export type ContactDetailsCountAggregateOutputType = {
  id: number;
  telegramChatIds: number;
  discordChatIds: number;
  userId: number;
  _all: number;
};

export type ContactDetailsAvgAggregateInputType = {
  id?: true;
  userId?: true;
};

export type ContactDetailsSumAggregateInputType = {
  id?: true;
  userId?: true;
};

export type ContactDetailsMinAggregateInputType = {
  id?: true;
  userId?: true;
};

export type ContactDetailsMaxAggregateInputType = {
  id?: true;
  userId?: true;
};

export type ContactDetailsCountAggregateInputType = {
  id?: true;
  telegramChatIds?: true;
  discordChatIds?: true;
  userId?: true;
  _all?: true;
};

export type ContactDetailsAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which ContactDetails to aggregate.
   */
  where?: Prisma.ContactDetailsWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ContactDetails to fetch.
   */
  orderBy?: Prisma.ContactDetailsOrderByWithRelationInput | Prisma.ContactDetailsOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.ContactDetailsWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ContactDetails from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ContactDetails.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned ContactDetails
   **/
  _count?: true | ContactDetailsCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: ContactDetailsAvgAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: ContactDetailsSumAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: ContactDetailsMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: ContactDetailsMaxAggregateInputType;
};

export type GetContactDetailsAggregateType<T extends ContactDetailsAggregateArgs> = {
  [P in keyof T & keyof AggregateContactDetails]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateContactDetails[P]>
    : Prisma.GetScalarType<T[P], AggregateContactDetails[P]>;
};

export type ContactDetailsGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.ContactDetailsWhereInput;
  orderBy?: Prisma.ContactDetailsOrderByWithAggregationInput | Prisma.ContactDetailsOrderByWithAggregationInput[];
  by: Prisma.ContactDetailsScalarFieldEnum[] | Prisma.ContactDetailsScalarFieldEnum;
  having?: Prisma.ContactDetailsScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: ContactDetailsCountAggregateInputType | true;
  _avg?: ContactDetailsAvgAggregateInputType;
  _sum?: ContactDetailsSumAggregateInputType;
  _min?: ContactDetailsMinAggregateInputType;
  _max?: ContactDetailsMaxAggregateInputType;
};

export type ContactDetailsGroupByOutputType = {
  id: number;
  telegramChatIds: string[];
  discordChatIds: string[];
  userId: number;
  _count: ContactDetailsCountAggregateOutputType | null;
  _avg: ContactDetailsAvgAggregateOutputType | null;
  _sum: ContactDetailsSumAggregateOutputType | null;
  _min: ContactDetailsMinAggregateOutputType | null;
  _max: ContactDetailsMaxAggregateOutputType | null;
};

type GetContactDetailsGroupByPayload<T extends ContactDetailsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ContactDetailsGroupByOutputType, T['by']> & {
      [P in keyof T & keyof ContactDetailsGroupByOutputType]: P extends '_count'
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], ContactDetailsGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], ContactDetailsGroupByOutputType[P]>;
    }
  >
>;

export type ContactDetailsWhereInput = {
  AND?: Prisma.ContactDetailsWhereInput | Prisma.ContactDetailsWhereInput[];
  OR?: Prisma.ContactDetailsWhereInput[];
  NOT?: Prisma.ContactDetailsWhereInput | Prisma.ContactDetailsWhereInput[];
  id?: Prisma.IntFilter<'ContactDetails'> | number;
  telegramChatIds?: Prisma.StringNullableListFilter<'ContactDetails'>;
  discordChatIds?: Prisma.StringNullableListFilter<'ContactDetails'>;
  userId?: Prisma.IntFilter<'ContactDetails'> | number;
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
};

export type ContactDetailsOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  telegramChatIds?: Prisma.SortOrder;
  discordChatIds?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  user?: Prisma.UserOrderByWithRelationInput;
};

export type ContactDetailsWhereUniqueInput = Prisma.AtLeast<
  {
    id?: number;
    userId?: number;
    AND?: Prisma.ContactDetailsWhereInput | Prisma.ContactDetailsWhereInput[];
    OR?: Prisma.ContactDetailsWhereInput[];
    NOT?: Prisma.ContactDetailsWhereInput | Prisma.ContactDetailsWhereInput[];
    telegramChatIds?: Prisma.StringNullableListFilter<'ContactDetails'>;
    discordChatIds?: Prisma.StringNullableListFilter<'ContactDetails'>;
    user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
  },
  'id' | 'userId'
>;

export type ContactDetailsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  telegramChatIds?: Prisma.SortOrder;
  discordChatIds?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  _count?: Prisma.ContactDetailsCountOrderByAggregateInput;
  _avg?: Prisma.ContactDetailsAvgOrderByAggregateInput;
  _max?: Prisma.ContactDetailsMaxOrderByAggregateInput;
  _min?: Prisma.ContactDetailsMinOrderByAggregateInput;
  _sum?: Prisma.ContactDetailsSumOrderByAggregateInput;
};

export type ContactDetailsScalarWhereWithAggregatesInput = {
  AND?: Prisma.ContactDetailsScalarWhereWithAggregatesInput | Prisma.ContactDetailsScalarWhereWithAggregatesInput[];
  OR?: Prisma.ContactDetailsScalarWhereWithAggregatesInput[];
  NOT?: Prisma.ContactDetailsScalarWhereWithAggregatesInput | Prisma.ContactDetailsScalarWhereWithAggregatesInput[];
  id?: Prisma.IntWithAggregatesFilter<'ContactDetails'> | number;
  telegramChatIds?: Prisma.StringNullableListFilter<'ContactDetails'>;
  discordChatIds?: Prisma.StringNullableListFilter<'ContactDetails'>;
  userId?: Prisma.IntWithAggregatesFilter<'ContactDetails'> | number;
};

export type ContactDetailsCreateInput = {
  telegramChatIds?: Prisma.ContactDetailsCreatetelegramChatIdsInput | string[];
  discordChatIds?: Prisma.ContactDetailsCreatediscordChatIdsInput | string[];
  user: Prisma.UserCreateNestedOneWithoutContactDetailsInput;
};

export type ContactDetailsUncheckedCreateInput = {
  id?: number;
  telegramChatIds?: Prisma.ContactDetailsCreatetelegramChatIdsInput | string[];
  discordChatIds?: Prisma.ContactDetailsCreatediscordChatIdsInput | string[];
  userId: number;
};

export type ContactDetailsUpdateInput = {
  telegramChatIds?: Prisma.ContactDetailsUpdatetelegramChatIdsInput | string[];
  discordChatIds?: Prisma.ContactDetailsUpdatediscordChatIdsInput | string[];
  user?: Prisma.UserUpdateOneRequiredWithoutContactDetailsNestedInput;
};

export type ContactDetailsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number;
  telegramChatIds?: Prisma.ContactDetailsUpdatetelegramChatIdsInput | string[];
  discordChatIds?: Prisma.ContactDetailsUpdatediscordChatIdsInput | string[];
  userId?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type ContactDetailsCreateManyInput = {
  id?: number;
  telegramChatIds?: Prisma.ContactDetailsCreatetelegramChatIdsInput | string[];
  discordChatIds?: Prisma.ContactDetailsCreatediscordChatIdsInput | string[];
  userId: number;
};

export type ContactDetailsUpdateManyMutationInput = {
  telegramChatIds?: Prisma.ContactDetailsUpdatetelegramChatIdsInput | string[];
  discordChatIds?: Prisma.ContactDetailsUpdatediscordChatIdsInput | string[];
};

export type ContactDetailsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number;
  telegramChatIds?: Prisma.ContactDetailsUpdatetelegramChatIdsInput | string[];
  discordChatIds?: Prisma.ContactDetailsUpdatediscordChatIdsInput | string[];
  userId?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type ContactDetailsListRelationFilter = {
  every?: Prisma.ContactDetailsWhereInput;
  some?: Prisma.ContactDetailsWhereInput;
  none?: Prisma.ContactDetailsWhereInput;
};

export type ContactDetailsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null;
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null;
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>;
  isEmpty?: boolean;
};

export type ContactDetailsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  telegramChatIds?: Prisma.SortOrder;
  discordChatIds?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
};

export type ContactDetailsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
};

export type ContactDetailsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
};

export type ContactDetailsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
};

export type ContactDetailsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
};

export type ContactDetailsCreateNestedManyWithoutUserInput = {
  create?:
    | Prisma.XOR<Prisma.ContactDetailsCreateWithoutUserInput, Prisma.ContactDetailsUncheckedCreateWithoutUserInput>
    | Prisma.ContactDetailsCreateWithoutUserInput[]
    | Prisma.ContactDetailsUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.ContactDetailsCreateOrConnectWithoutUserInput
    | Prisma.ContactDetailsCreateOrConnectWithoutUserInput[];
  createMany?: Prisma.ContactDetailsCreateManyUserInputEnvelope;
  connect?: Prisma.ContactDetailsWhereUniqueInput | Prisma.ContactDetailsWhereUniqueInput[];
};

export type ContactDetailsUncheckedCreateNestedManyWithoutUserInput = {
  create?:
    | Prisma.XOR<Prisma.ContactDetailsCreateWithoutUserInput, Prisma.ContactDetailsUncheckedCreateWithoutUserInput>
    | Prisma.ContactDetailsCreateWithoutUserInput[]
    | Prisma.ContactDetailsUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.ContactDetailsCreateOrConnectWithoutUserInput
    | Prisma.ContactDetailsCreateOrConnectWithoutUserInput[];
  createMany?: Prisma.ContactDetailsCreateManyUserInputEnvelope;
  connect?: Prisma.ContactDetailsWhereUniqueInput | Prisma.ContactDetailsWhereUniqueInput[];
};

export type ContactDetailsUpdateManyWithoutUserNestedInput = {
  create?:
    | Prisma.XOR<Prisma.ContactDetailsCreateWithoutUserInput, Prisma.ContactDetailsUncheckedCreateWithoutUserInput>
    | Prisma.ContactDetailsCreateWithoutUserInput[]
    | Prisma.ContactDetailsUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.ContactDetailsCreateOrConnectWithoutUserInput
    | Prisma.ContactDetailsCreateOrConnectWithoutUserInput[];
  upsert?:
    | Prisma.ContactDetailsUpsertWithWhereUniqueWithoutUserInput
    | Prisma.ContactDetailsUpsertWithWhereUniqueWithoutUserInput[];
  createMany?: Prisma.ContactDetailsCreateManyUserInputEnvelope;
  set?: Prisma.ContactDetailsWhereUniqueInput | Prisma.ContactDetailsWhereUniqueInput[];
  disconnect?: Prisma.ContactDetailsWhereUniqueInput | Prisma.ContactDetailsWhereUniqueInput[];
  delete?: Prisma.ContactDetailsWhereUniqueInput | Prisma.ContactDetailsWhereUniqueInput[];
  connect?: Prisma.ContactDetailsWhereUniqueInput | Prisma.ContactDetailsWhereUniqueInput[];
  update?:
    | Prisma.ContactDetailsUpdateWithWhereUniqueWithoutUserInput
    | Prisma.ContactDetailsUpdateWithWhereUniqueWithoutUserInput[];
  updateMany?:
    | Prisma.ContactDetailsUpdateManyWithWhereWithoutUserInput
    | Prisma.ContactDetailsUpdateManyWithWhereWithoutUserInput[];
  deleteMany?: Prisma.ContactDetailsScalarWhereInput | Prisma.ContactDetailsScalarWhereInput[];
};

export type ContactDetailsUncheckedUpdateManyWithoutUserNestedInput = {
  create?:
    | Prisma.XOR<Prisma.ContactDetailsCreateWithoutUserInput, Prisma.ContactDetailsUncheckedCreateWithoutUserInput>
    | Prisma.ContactDetailsCreateWithoutUserInput[]
    | Prisma.ContactDetailsUncheckedCreateWithoutUserInput[];
  connectOrCreate?:
    | Prisma.ContactDetailsCreateOrConnectWithoutUserInput
    | Prisma.ContactDetailsCreateOrConnectWithoutUserInput[];
  upsert?:
    | Prisma.ContactDetailsUpsertWithWhereUniqueWithoutUserInput
    | Prisma.ContactDetailsUpsertWithWhereUniqueWithoutUserInput[];
  createMany?: Prisma.ContactDetailsCreateManyUserInputEnvelope;
  set?: Prisma.ContactDetailsWhereUniqueInput | Prisma.ContactDetailsWhereUniqueInput[];
  disconnect?: Prisma.ContactDetailsWhereUniqueInput | Prisma.ContactDetailsWhereUniqueInput[];
  delete?: Prisma.ContactDetailsWhereUniqueInput | Prisma.ContactDetailsWhereUniqueInput[];
  connect?: Prisma.ContactDetailsWhereUniqueInput | Prisma.ContactDetailsWhereUniqueInput[];
  update?:
    | Prisma.ContactDetailsUpdateWithWhereUniqueWithoutUserInput
    | Prisma.ContactDetailsUpdateWithWhereUniqueWithoutUserInput[];
  updateMany?:
    | Prisma.ContactDetailsUpdateManyWithWhereWithoutUserInput
    | Prisma.ContactDetailsUpdateManyWithWhereWithoutUserInput[];
  deleteMany?: Prisma.ContactDetailsScalarWhereInput | Prisma.ContactDetailsScalarWhereInput[];
};

export type ContactDetailsCreatetelegramChatIdsInput = {
  set: string[];
};

export type ContactDetailsCreatediscordChatIdsInput = {
  set: string[];
};

export type ContactDetailsUpdatetelegramChatIdsInput = {
  set?: string[];
  push?: string | string[];
};

export type ContactDetailsUpdatediscordChatIdsInput = {
  set?: string[];
  push?: string | string[];
};

export type ContactDetailsCreateWithoutUserInput = {
  telegramChatIds?: Prisma.ContactDetailsCreatetelegramChatIdsInput | string[];
  discordChatIds?: Prisma.ContactDetailsCreatediscordChatIdsInput | string[];
};

export type ContactDetailsUncheckedCreateWithoutUserInput = {
  id?: number;
  telegramChatIds?: Prisma.ContactDetailsCreatetelegramChatIdsInput | string[];
  discordChatIds?: Prisma.ContactDetailsCreatediscordChatIdsInput | string[];
};

export type ContactDetailsCreateOrConnectWithoutUserInput = {
  where: Prisma.ContactDetailsWhereUniqueInput;
  create: Prisma.XOR<Prisma.ContactDetailsCreateWithoutUserInput, Prisma.ContactDetailsUncheckedCreateWithoutUserInput>;
};

export type ContactDetailsCreateManyUserInputEnvelope = {
  data: Prisma.ContactDetailsCreateManyUserInput | Prisma.ContactDetailsCreateManyUserInput[];
  skipDuplicates?: boolean;
};

export type ContactDetailsUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ContactDetailsWhereUniqueInput;
  update: Prisma.XOR<Prisma.ContactDetailsUpdateWithoutUserInput, Prisma.ContactDetailsUncheckedUpdateWithoutUserInput>;
  create: Prisma.XOR<Prisma.ContactDetailsCreateWithoutUserInput, Prisma.ContactDetailsUncheckedCreateWithoutUserInput>;
};

export type ContactDetailsUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ContactDetailsWhereUniqueInput;
  data: Prisma.XOR<Prisma.ContactDetailsUpdateWithoutUserInput, Prisma.ContactDetailsUncheckedUpdateWithoutUserInput>;
};

export type ContactDetailsUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ContactDetailsScalarWhereInput;
  data: Prisma.XOR<
    Prisma.ContactDetailsUpdateManyMutationInput,
    Prisma.ContactDetailsUncheckedUpdateManyWithoutUserInput
  >;
};

export type ContactDetailsScalarWhereInput = {
  AND?: Prisma.ContactDetailsScalarWhereInput | Prisma.ContactDetailsScalarWhereInput[];
  OR?: Prisma.ContactDetailsScalarWhereInput[];
  NOT?: Prisma.ContactDetailsScalarWhereInput | Prisma.ContactDetailsScalarWhereInput[];
  id?: Prisma.IntFilter<'ContactDetails'> | number;
  telegramChatIds?: Prisma.StringNullableListFilter<'ContactDetails'>;
  discordChatIds?: Prisma.StringNullableListFilter<'ContactDetails'>;
  userId?: Prisma.IntFilter<'ContactDetails'> | number;
};

export type ContactDetailsCreateManyUserInput = {
  id?: number;
  telegramChatIds?: Prisma.ContactDetailsCreatetelegramChatIdsInput | string[];
  discordChatIds?: Prisma.ContactDetailsCreatediscordChatIdsInput | string[];
};

export type ContactDetailsUpdateWithoutUserInput = {
  telegramChatIds?: Prisma.ContactDetailsUpdatetelegramChatIdsInput | string[];
  discordChatIds?: Prisma.ContactDetailsUpdatediscordChatIdsInput | string[];
};

export type ContactDetailsUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number;
  telegramChatIds?: Prisma.ContactDetailsUpdatetelegramChatIdsInput | string[];
  discordChatIds?: Prisma.ContactDetailsUpdatediscordChatIdsInput | string[];
};

export type ContactDetailsUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number;
  telegramChatIds?: Prisma.ContactDetailsUpdatetelegramChatIdsInput | string[];
  discordChatIds?: Prisma.ContactDetailsUpdatediscordChatIdsInput | string[];
};

export type ContactDetailsSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    telegramChatIds?: boolean;
    discordChatIds?: boolean;
    userId?: boolean;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['contactDetails']
>;

export type ContactDetailsSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    telegramChatIds?: boolean;
    discordChatIds?: boolean;
    userId?: boolean;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['contactDetails']
>;

export type ContactDetailsSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    telegramChatIds?: boolean;
    discordChatIds?: boolean;
    userId?: boolean;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['contactDetails']
>;

export type ContactDetailsSelectScalar = {
  id?: boolean;
  telegramChatIds?: boolean;
  discordChatIds?: boolean;
  userId?: boolean;
};

export type ContactDetailsOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'id' | 'telegramChatIds' | 'discordChatIds' | 'userId',
  ExtArgs['result']['contactDetails']
>;
export type ContactDetailsInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};
export type ContactDetailsIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};
export type ContactDetailsIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};

export type $ContactDetailsPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'ContactDetails';
  objects: {
    user: Prisma.$UserPayload<ExtArgs>;
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: number;
      telegramChatIds: string[];
      discordChatIds: string[];
      userId: number;
    },
    ExtArgs['result']['contactDetails']
  >;
  composites: {};
};

export type ContactDetailsGetPayload<S extends boolean | null | undefined | ContactDetailsDefaultArgs> =
  runtime.Types.Result.GetResult<Prisma.$ContactDetailsPayload, S>;

export type ContactDetailsCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<ContactDetailsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: ContactDetailsCountAggregateInputType | true;
};

export interface ContactDetailsDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['ContactDetails'];
    meta: { name: 'ContactDetails' };
  };
  /**
   * Find zero or one ContactDetails that matches the filter.
   * @param {ContactDetailsFindUniqueArgs} args - Arguments to find a ContactDetails
   * @example
   * // Get one ContactDetails
   * const contactDetails = await prisma.contactDetails.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ContactDetailsFindUniqueArgs>(
    args: Prisma.SelectSubset<T, ContactDetailsFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__ContactDetailsClient<
    runtime.Types.Result.GetResult<Prisma.$ContactDetailsPayload<ExtArgs>, T, 'findUnique', GlobalOmitOptions> | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one ContactDetails that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ContactDetailsFindUniqueOrThrowArgs} args - Arguments to find a ContactDetails
   * @example
   * // Get one ContactDetails
   * const contactDetails = await prisma.contactDetails.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ContactDetailsFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, ContactDetailsFindUniqueOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__ContactDetailsClient<
    runtime.Types.Result.GetResult<Prisma.$ContactDetailsPayload<ExtArgs>, T, 'findUniqueOrThrow', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first ContactDetails that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactDetailsFindFirstArgs} args - Arguments to find a ContactDetails
   * @example
   * // Get one ContactDetails
   * const contactDetails = await prisma.contactDetails.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ContactDetailsFindFirstArgs>(
    args?: Prisma.SelectSubset<T, ContactDetailsFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__ContactDetailsClient<
    runtime.Types.Result.GetResult<Prisma.$ContactDetailsPayload<ExtArgs>, T, 'findFirst', GlobalOmitOptions> | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first ContactDetails that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactDetailsFindFirstOrThrowArgs} args - Arguments to find a ContactDetails
   * @example
   * // Get one ContactDetails
   * const contactDetails = await prisma.contactDetails.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ContactDetailsFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, ContactDetailsFindFirstOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__ContactDetailsClient<
    runtime.Types.Result.GetResult<Prisma.$ContactDetailsPayload<ExtArgs>, T, 'findFirstOrThrow', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more ContactDetails that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactDetailsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ContactDetails
   * const contactDetails = await prisma.contactDetails.findMany()
   *
   * // Get first 10 ContactDetails
   * const contactDetails = await prisma.contactDetails.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const contactDetailsWithIdOnly = await prisma.contactDetails.findMany({ select: { id: true } })
   *
   */
  findMany<T extends ContactDetailsFindManyArgs>(
    args?: Prisma.SelectSubset<T, ContactDetailsFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<Prisma.$ContactDetailsPayload<ExtArgs>, T, 'findMany', GlobalOmitOptions>
  >;

  /**
   * Create a ContactDetails.
   * @param {ContactDetailsCreateArgs} args - Arguments to create a ContactDetails.
   * @example
   * // Create one ContactDetails
   * const ContactDetails = await prisma.contactDetails.create({
   *   data: {
   *     // ... data to create a ContactDetails
   *   }
   * })
   *
   */
  create<T extends ContactDetailsCreateArgs>(
    args: Prisma.SelectSubset<T, ContactDetailsCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__ContactDetailsClient<
    runtime.Types.Result.GetResult<Prisma.$ContactDetailsPayload<ExtArgs>, T, 'create', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many ContactDetails.
   * @param {ContactDetailsCreateManyArgs} args - Arguments to create many ContactDetails.
   * @example
   * // Create many ContactDetails
   * const contactDetails = await prisma.contactDetails.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends ContactDetailsCreateManyArgs>(
    args?: Prisma.SelectSubset<T, ContactDetailsCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many ContactDetails and returns the data saved in the database.
   * @param {ContactDetailsCreateManyAndReturnArgs} args - Arguments to create many ContactDetails.
   * @example
   * // Create many ContactDetails
   * const contactDetails = await prisma.contactDetails.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many ContactDetails and only return the `id`
   * const contactDetailsWithIdOnly = await prisma.contactDetails.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends ContactDetailsCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, ContactDetailsCreateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<Prisma.$ContactDetailsPayload<ExtArgs>, T, 'createManyAndReturn', GlobalOmitOptions>
  >;

  /**
   * Delete a ContactDetails.
   * @param {ContactDetailsDeleteArgs} args - Arguments to delete one ContactDetails.
   * @example
   * // Delete one ContactDetails
   * const ContactDetails = await prisma.contactDetails.delete({
   *   where: {
   *     // ... filter to delete one ContactDetails
   *   }
   * })
   *
   */
  delete<T extends ContactDetailsDeleteArgs>(
    args: Prisma.SelectSubset<T, ContactDetailsDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__ContactDetailsClient<
    runtime.Types.Result.GetResult<Prisma.$ContactDetailsPayload<ExtArgs>, T, 'delete', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one ContactDetails.
   * @param {ContactDetailsUpdateArgs} args - Arguments to update one ContactDetails.
   * @example
   * // Update one ContactDetails
   * const contactDetails = await prisma.contactDetails.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends ContactDetailsUpdateArgs>(
    args: Prisma.SelectSubset<T, ContactDetailsUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__ContactDetailsClient<
    runtime.Types.Result.GetResult<Prisma.$ContactDetailsPayload<ExtArgs>, T, 'update', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more ContactDetails.
   * @param {ContactDetailsDeleteManyArgs} args - Arguments to filter ContactDetails to delete.
   * @example
   * // Delete a few ContactDetails
   * const { count } = await prisma.contactDetails.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends ContactDetailsDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, ContactDetailsDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more ContactDetails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactDetailsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ContactDetails
   * const contactDetails = await prisma.contactDetails.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends ContactDetailsUpdateManyArgs>(
    args: Prisma.SelectSubset<T, ContactDetailsUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more ContactDetails and returns the data updated in the database.
   * @param {ContactDetailsUpdateManyAndReturnArgs} args - Arguments to update many ContactDetails.
   * @example
   * // Update many ContactDetails
   * const contactDetails = await prisma.contactDetails.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more ContactDetails and only return the `id`
   * const contactDetailsWithIdOnly = await prisma.contactDetails.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends ContactDetailsUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, ContactDetailsUpdateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<Prisma.$ContactDetailsPayload<ExtArgs>, T, 'updateManyAndReturn', GlobalOmitOptions>
  >;

  /**
   * Create or update one ContactDetails.
   * @param {ContactDetailsUpsertArgs} args - Arguments to update or create a ContactDetails.
   * @example
   * // Update or create a ContactDetails
   * const contactDetails = await prisma.contactDetails.upsert({
   *   create: {
   *     // ... data to create a ContactDetails
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ContactDetails we want to update
   *   }
   * })
   */
  upsert<T extends ContactDetailsUpsertArgs>(
    args: Prisma.SelectSubset<T, ContactDetailsUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__ContactDetailsClient<
    runtime.Types.Result.GetResult<Prisma.$ContactDetailsPayload<ExtArgs>, T, 'upsert', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of ContactDetails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactDetailsCountArgs} args - Arguments to filter ContactDetails to count.
   * @example
   * // Count the number of ContactDetails
   * const count = await prisma.contactDetails.count({
   *   where: {
   *     // ... the filter for the ContactDetails we want to count
   *   }
   * })
   **/
  count<T extends ContactDetailsCountArgs>(
    args?: Prisma.Subset<T, ContactDetailsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ContactDetailsCountAggregateOutputType>
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a ContactDetails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactDetailsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends ContactDetailsAggregateArgs>(
    args: Prisma.Subset<T, ContactDetailsAggregateArgs>,
  ): Prisma.PrismaPromise<GetContactDetailsAggregateType<T>>;

  /**
   * Group by ContactDetails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContactDetailsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends ContactDetailsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<T>>, Prisma.Extends<'take', Prisma.Keys<T>>>,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ContactDetailsGroupByArgs['orderBy'] }
      : { orderBy?: ContactDetailsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, ContactDetailsGroupByArgs, OrderByArg> & InputErrors,
  ): {} extends InputErrors ? GetContactDetailsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the ContactDetails model
   */
  readonly fields: ContactDetailsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ContactDetails.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ContactDetailsClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise';
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__UserClient<
    runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, 'findUniqueOrThrow', GlobalOmitOptions> | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the ContactDetails model
 */
export interface ContactDetailsFieldRefs {
  readonly id: Prisma.FieldRef<'ContactDetails', 'Int'>;
  readonly telegramChatIds: Prisma.FieldRef<'ContactDetails', 'String[]'>;
  readonly discordChatIds: Prisma.FieldRef<'ContactDetails', 'String[]'>;
  readonly userId: Prisma.FieldRef<'ContactDetails', 'Int'>;
}

// Custom InputTypes
/**
 * ContactDetails findUnique
 */
export type ContactDetailsFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ContactDetails
   */
  select?: Prisma.ContactDetailsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ContactDetails
   */
  omit?: Prisma.ContactDetailsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactDetailsInclude<ExtArgs> | null;
  /**
   * Filter, which ContactDetails to fetch.
   */
  where: Prisma.ContactDetailsWhereUniqueInput;
};

/**
 * ContactDetails findUniqueOrThrow
 */
export type ContactDetailsFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ContactDetails
   */
  select?: Prisma.ContactDetailsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ContactDetails
   */
  omit?: Prisma.ContactDetailsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactDetailsInclude<ExtArgs> | null;
  /**
   * Filter, which ContactDetails to fetch.
   */
  where: Prisma.ContactDetailsWhereUniqueInput;
};

/**
 * ContactDetails findFirst
 */
export type ContactDetailsFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ContactDetails
   */
  select?: Prisma.ContactDetailsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ContactDetails
   */
  omit?: Prisma.ContactDetailsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactDetailsInclude<ExtArgs> | null;
  /**
   * Filter, which ContactDetails to fetch.
   */
  where?: Prisma.ContactDetailsWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ContactDetails to fetch.
   */
  orderBy?: Prisma.ContactDetailsOrderByWithRelationInput | Prisma.ContactDetailsOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for ContactDetails.
   */
  cursor?: Prisma.ContactDetailsWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ContactDetails from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ContactDetails.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ContactDetails.
   */
  distinct?: Prisma.ContactDetailsScalarFieldEnum | Prisma.ContactDetailsScalarFieldEnum[];
};

/**
 * ContactDetails findFirstOrThrow
 */
export type ContactDetailsFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ContactDetails
   */
  select?: Prisma.ContactDetailsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ContactDetails
   */
  omit?: Prisma.ContactDetailsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactDetailsInclude<ExtArgs> | null;
  /**
   * Filter, which ContactDetails to fetch.
   */
  where?: Prisma.ContactDetailsWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ContactDetails to fetch.
   */
  orderBy?: Prisma.ContactDetailsOrderByWithRelationInput | Prisma.ContactDetailsOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for ContactDetails.
   */
  cursor?: Prisma.ContactDetailsWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ContactDetails from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ContactDetails.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of ContactDetails.
   */
  distinct?: Prisma.ContactDetailsScalarFieldEnum | Prisma.ContactDetailsScalarFieldEnum[];
};

/**
 * ContactDetails findMany
 */
export type ContactDetailsFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ContactDetails
   */
  select?: Prisma.ContactDetailsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ContactDetails
   */
  omit?: Prisma.ContactDetailsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactDetailsInclude<ExtArgs> | null;
  /**
   * Filter, which ContactDetails to fetch.
   */
  where?: Prisma.ContactDetailsWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of ContactDetails to fetch.
   */
  orderBy?: Prisma.ContactDetailsOrderByWithRelationInput | Prisma.ContactDetailsOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing ContactDetails.
   */
  cursor?: Prisma.ContactDetailsWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` ContactDetails from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` ContactDetails.
   */
  skip?: number;
  distinct?: Prisma.ContactDetailsScalarFieldEnum | Prisma.ContactDetailsScalarFieldEnum[];
};

/**
 * ContactDetails create
 */
export type ContactDetailsCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ContactDetails
   */
  select?: Prisma.ContactDetailsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ContactDetails
   */
  omit?: Prisma.ContactDetailsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactDetailsInclude<ExtArgs> | null;
  /**
   * The data needed to create a ContactDetails.
   */
  data: Prisma.XOR<Prisma.ContactDetailsCreateInput, Prisma.ContactDetailsUncheckedCreateInput>;
};

/**
 * ContactDetails createMany
 */
export type ContactDetailsCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many ContactDetails.
   */
  data: Prisma.ContactDetailsCreateManyInput | Prisma.ContactDetailsCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * ContactDetails createManyAndReturn
 */
export type ContactDetailsCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ContactDetails
   */
  select?: Prisma.ContactDetailsSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the ContactDetails
   */
  omit?: Prisma.ContactDetailsOmit<ExtArgs> | null;
  /**
   * The data used to create many ContactDetails.
   */
  data: Prisma.ContactDetailsCreateManyInput | Prisma.ContactDetailsCreateManyInput[];
  skipDuplicates?: boolean;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactDetailsIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * ContactDetails update
 */
export type ContactDetailsUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ContactDetails
   */
  select?: Prisma.ContactDetailsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ContactDetails
   */
  omit?: Prisma.ContactDetailsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactDetailsInclude<ExtArgs> | null;
  /**
   * The data needed to update a ContactDetails.
   */
  data: Prisma.XOR<Prisma.ContactDetailsUpdateInput, Prisma.ContactDetailsUncheckedUpdateInput>;
  /**
   * Choose, which ContactDetails to update.
   */
  where: Prisma.ContactDetailsWhereUniqueInput;
};

/**
 * ContactDetails updateMany
 */
export type ContactDetailsUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update ContactDetails.
   */
  data: Prisma.XOR<Prisma.ContactDetailsUpdateManyMutationInput, Prisma.ContactDetailsUncheckedUpdateManyInput>;
  /**
   * Filter which ContactDetails to update
   */
  where?: Prisma.ContactDetailsWhereInput;
  /**
   * Limit how many ContactDetails to update.
   */
  limit?: number;
};

/**
 * ContactDetails updateManyAndReturn
 */
export type ContactDetailsUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ContactDetails
   */
  select?: Prisma.ContactDetailsSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the ContactDetails
   */
  omit?: Prisma.ContactDetailsOmit<ExtArgs> | null;
  /**
   * The data used to update ContactDetails.
   */
  data: Prisma.XOR<Prisma.ContactDetailsUpdateManyMutationInput, Prisma.ContactDetailsUncheckedUpdateManyInput>;
  /**
   * Filter which ContactDetails to update
   */
  where?: Prisma.ContactDetailsWhereInput;
  /**
   * Limit how many ContactDetails to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactDetailsIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * ContactDetails upsert
 */
export type ContactDetailsUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ContactDetails
   */
  select?: Prisma.ContactDetailsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ContactDetails
   */
  omit?: Prisma.ContactDetailsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactDetailsInclude<ExtArgs> | null;
  /**
   * The filter to search for the ContactDetails to update in case it exists.
   */
  where: Prisma.ContactDetailsWhereUniqueInput;
  /**
   * In case the ContactDetails found by the `where` argument doesn't exist, create a new ContactDetails with this data.
   */
  create: Prisma.XOR<Prisma.ContactDetailsCreateInput, Prisma.ContactDetailsUncheckedCreateInput>;
  /**
   * In case the ContactDetails was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ContactDetailsUpdateInput, Prisma.ContactDetailsUncheckedUpdateInput>;
};

/**
 * ContactDetails delete
 */
export type ContactDetailsDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ContactDetails
   */
  select?: Prisma.ContactDetailsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ContactDetails
   */
  omit?: Prisma.ContactDetailsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactDetailsInclude<ExtArgs> | null;
  /**
   * Filter which ContactDetails to delete.
   */
  where: Prisma.ContactDetailsWhereUniqueInput;
};

/**
 * ContactDetails deleteMany
 */
export type ContactDetailsDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which ContactDetails to delete
   */
  where?: Prisma.ContactDetailsWhereInput;
  /**
   * Limit how many ContactDetails to delete.
   */
  limit?: number;
};

/**
 * ContactDetails without action
 */
export type ContactDetailsDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ContactDetails
   */
  select?: Prisma.ContactDetailsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ContactDetails
   */
  omit?: Prisma.ContactDetailsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContactDetailsInclude<ExtArgs> | null;
};
