/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `Errors` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client';
import type * as $Enums from '../enums.js';
import type * as Prisma from '../internal/prismaNamespace.js';

/**
 * Model Errors
 *
 */
export type ErrorsModel = runtime.Types.Result.DefaultSelection<Prisma.$ErrorsPayload>;

export type AggregateErrors = {
  _count: ErrorsCountAggregateOutputType | null;
  _avg: ErrorsAvgAggregateOutputType | null;
  _sum: ErrorsSumAggregateOutputType | null;
  _min: ErrorsMinAggregateOutputType | null;
  _max: ErrorsMaxAggregateOutputType | null;
};

export type ErrorsAvgAggregateOutputType = {
  id: number | null;
  userId: number | null;
};

export type ErrorsSumAggregateOutputType = {
  id: number | null;
  userId: number | null;
};

export type ErrorsMinAggregateOutputType = {
  id: number | null;
  errorName: string | null;
  errorDesc: string | null;
  errorPriority: $Enums.ErrorPriority | null;
  errorDateAndTime: Date | null;
  errorResolveDateAndTime: Date | null;
  userId: number | null;
};

export type ErrorsMaxAggregateOutputType = {
  id: number | null;
  errorName: string | null;
  errorDesc: string | null;
  errorPriority: $Enums.ErrorPriority | null;
  errorDateAndTime: Date | null;
  errorResolveDateAndTime: Date | null;
  userId: number | null;
};

export type ErrorsCountAggregateOutputType = {
  id: number;
  errorName: number;
  errorDesc: number;
  errorPriority: number;
  errorDateAndTime: number;
  errorResolveDateAndTime: number;
  userId: number;
  _all: number;
};

export type ErrorsAvgAggregateInputType = {
  id?: true;
  userId?: true;
};

export type ErrorsSumAggregateInputType = {
  id?: true;
  userId?: true;
};

export type ErrorsMinAggregateInputType = {
  id?: true;
  errorName?: true;
  errorDesc?: true;
  errorPriority?: true;
  errorDateAndTime?: true;
  errorResolveDateAndTime?: true;
  userId?: true;
};

export type ErrorsMaxAggregateInputType = {
  id?: true;
  errorName?: true;
  errorDesc?: true;
  errorPriority?: true;
  errorDateAndTime?: true;
  errorResolveDateAndTime?: true;
  userId?: true;
};

export type ErrorsCountAggregateInputType = {
  id?: true;
  errorName?: true;
  errorDesc?: true;
  errorPriority?: true;
  errorDateAndTime?: true;
  errorResolveDateAndTime?: true;
  userId?: true;
  _all?: true;
};

export type ErrorsAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which Errors to aggregate.
   */
  where?: Prisma.ErrorsWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Errors to fetch.
   */
  orderBy?: Prisma.ErrorsOrderByWithRelationInput | Prisma.ErrorsOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.ErrorsWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Errors from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Errors.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned Errors
   **/
  _count?: true | ErrorsCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: ErrorsAvgAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: ErrorsSumAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: ErrorsMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: ErrorsMaxAggregateInputType;
};

export type GetErrorsAggregateType<T extends ErrorsAggregateArgs> = {
  [P in keyof T & keyof AggregateErrors]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateErrors[P]>
    : Prisma.GetScalarType<T[P], AggregateErrors[P]>;
};

export type ErrorsGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.ErrorsWhereInput;
  orderBy?: Prisma.ErrorsOrderByWithAggregationInput | Prisma.ErrorsOrderByWithAggregationInput[];
  by: Prisma.ErrorsScalarFieldEnum[] | Prisma.ErrorsScalarFieldEnum;
  having?: Prisma.ErrorsScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: ErrorsCountAggregateInputType | true;
  _avg?: ErrorsAvgAggregateInputType;
  _sum?: ErrorsSumAggregateInputType;
  _min?: ErrorsMinAggregateInputType;
  _max?: ErrorsMaxAggregateInputType;
};

export type ErrorsGroupByOutputType = {
  id: number;
  errorName: string;
  errorDesc: string;
  errorPriority: $Enums.ErrorPriority | null;
  errorDateAndTime: Date;
  errorResolveDateAndTime: Date | null;
  userId: number;
  _count: ErrorsCountAggregateOutputType | null;
  _avg: ErrorsAvgAggregateOutputType | null;
  _sum: ErrorsSumAggregateOutputType | null;
  _min: ErrorsMinAggregateOutputType | null;
  _max: ErrorsMaxAggregateOutputType | null;
};

type GetErrorsGroupByPayload<T extends ErrorsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ErrorsGroupByOutputType, T['by']> & {
      [P in keyof T & keyof ErrorsGroupByOutputType]: P extends '_count'
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], ErrorsGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], ErrorsGroupByOutputType[P]>;
    }
  >
>;

export type ErrorsWhereInput = {
  AND?: Prisma.ErrorsWhereInput | Prisma.ErrorsWhereInput[];
  OR?: Prisma.ErrorsWhereInput[];
  NOT?: Prisma.ErrorsWhereInput | Prisma.ErrorsWhereInput[];
  id?: Prisma.IntFilter<'Errors'> | number;
  errorName?: Prisma.StringFilter<'Errors'> | string;
  errorDesc?: Prisma.StringFilter<'Errors'> | string;
  errorPriority?: Prisma.EnumErrorPriorityNullableFilter<'Errors'> | $Enums.ErrorPriority | null;
  errorDateAndTime?: Prisma.DateTimeFilter<'Errors'> | Date | string;
  errorResolveDateAndTime?: Prisma.DateTimeNullableFilter<'Errors'> | Date | string | null;
  userId?: Prisma.IntFilter<'Errors'> | number;
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
};

export type ErrorsOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  errorName?: Prisma.SortOrder;
  errorDesc?: Prisma.SortOrder;
  errorPriority?: Prisma.SortOrderInput | Prisma.SortOrder;
  errorDateAndTime?: Prisma.SortOrder;
  errorResolveDateAndTime?: Prisma.SortOrderInput | Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  user?: Prisma.UserOrderByWithRelationInput;
};

export type ErrorsWhereUniqueInput = Prisma.AtLeast<
  {
    id?: number;
    AND?: Prisma.ErrorsWhereInput | Prisma.ErrorsWhereInput[];
    OR?: Prisma.ErrorsWhereInput[];
    NOT?: Prisma.ErrorsWhereInput | Prisma.ErrorsWhereInput[];
    errorName?: Prisma.StringFilter<'Errors'> | string;
    errorDesc?: Prisma.StringFilter<'Errors'> | string;
    errorPriority?: Prisma.EnumErrorPriorityNullableFilter<'Errors'> | $Enums.ErrorPriority | null;
    errorDateAndTime?: Prisma.DateTimeFilter<'Errors'> | Date | string;
    errorResolveDateAndTime?: Prisma.DateTimeNullableFilter<'Errors'> | Date | string | null;
    userId?: Prisma.IntFilter<'Errors'> | number;
    user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>;
  },
  'id'
>;

export type ErrorsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  errorName?: Prisma.SortOrder;
  errorDesc?: Prisma.SortOrder;
  errorPriority?: Prisma.SortOrderInput | Prisma.SortOrder;
  errorDateAndTime?: Prisma.SortOrder;
  errorResolveDateAndTime?: Prisma.SortOrderInput | Prisma.SortOrder;
  userId?: Prisma.SortOrder;
  _count?: Prisma.ErrorsCountOrderByAggregateInput;
  _avg?: Prisma.ErrorsAvgOrderByAggregateInput;
  _max?: Prisma.ErrorsMaxOrderByAggregateInput;
  _min?: Prisma.ErrorsMinOrderByAggregateInput;
  _sum?: Prisma.ErrorsSumOrderByAggregateInput;
};

export type ErrorsScalarWhereWithAggregatesInput = {
  AND?: Prisma.ErrorsScalarWhereWithAggregatesInput | Prisma.ErrorsScalarWhereWithAggregatesInput[];
  OR?: Prisma.ErrorsScalarWhereWithAggregatesInput[];
  NOT?: Prisma.ErrorsScalarWhereWithAggregatesInput | Prisma.ErrorsScalarWhereWithAggregatesInput[];
  id?: Prisma.IntWithAggregatesFilter<'Errors'> | number;
  errorName?: Prisma.StringWithAggregatesFilter<'Errors'> | string;
  errorDesc?: Prisma.StringWithAggregatesFilter<'Errors'> | string;
  errorPriority?: Prisma.EnumErrorPriorityNullableWithAggregatesFilter<'Errors'> | $Enums.ErrorPriority | null;
  errorDateAndTime?: Prisma.DateTimeWithAggregatesFilter<'Errors'> | Date | string;
  errorResolveDateAndTime?: Prisma.DateTimeNullableWithAggregatesFilter<'Errors'> | Date | string | null;
  userId?: Prisma.IntWithAggregatesFilter<'Errors'> | number;
};

export type ErrorsCreateInput = {
  errorName: string;
  errorDesc: string;
  errorPriority?: $Enums.ErrorPriority | null;
  errorDateAndTime?: Date | string;
  errorResolveDateAndTime?: Date | string | null;
  user: Prisma.UserCreateNestedOneWithoutErrorsInput;
};

export type ErrorsUncheckedCreateInput = {
  id?: number;
  errorName: string;
  errorDesc: string;
  errorPriority?: $Enums.ErrorPriority | null;
  errorDateAndTime?: Date | string;
  errorResolveDateAndTime?: Date | string | null;
  userId: number;
};

export type ErrorsUpdateInput = {
  errorName?: Prisma.StringFieldUpdateOperationsInput | string;
  errorDesc?: Prisma.StringFieldUpdateOperationsInput | string;
  errorPriority?: Prisma.NullableEnumErrorPriorityFieldUpdateOperationsInput | $Enums.ErrorPriority | null;
  errorDateAndTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  errorResolveDateAndTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  user?: Prisma.UserUpdateOneRequiredWithoutErrorsNestedInput;
};

export type ErrorsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number;
  errorName?: Prisma.StringFieldUpdateOperationsInput | string;
  errorDesc?: Prisma.StringFieldUpdateOperationsInput | string;
  errorPriority?: Prisma.NullableEnumErrorPriorityFieldUpdateOperationsInput | $Enums.ErrorPriority | null;
  errorDateAndTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  errorResolveDateAndTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  userId?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type ErrorsCreateManyInput = {
  id?: number;
  errorName: string;
  errorDesc: string;
  errorPriority?: $Enums.ErrorPriority | null;
  errorDateAndTime?: Date | string;
  errorResolveDateAndTime?: Date | string | null;
  userId: number;
};

export type ErrorsUpdateManyMutationInput = {
  errorName?: Prisma.StringFieldUpdateOperationsInput | string;
  errorDesc?: Prisma.StringFieldUpdateOperationsInput | string;
  errorPriority?: Prisma.NullableEnumErrorPriorityFieldUpdateOperationsInput | $Enums.ErrorPriority | null;
  errorDateAndTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  errorResolveDateAndTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
};

export type ErrorsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number;
  errorName?: Prisma.StringFieldUpdateOperationsInput | string;
  errorDesc?: Prisma.StringFieldUpdateOperationsInput | string;
  errorPriority?: Prisma.NullableEnumErrorPriorityFieldUpdateOperationsInput | $Enums.ErrorPriority | null;
  errorDateAndTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  errorResolveDateAndTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
  userId?: Prisma.IntFieldUpdateOperationsInput | number;
};

export type ErrorsListRelationFilter = {
  every?: Prisma.ErrorsWhereInput;
  some?: Prisma.ErrorsWhereInput;
  none?: Prisma.ErrorsWhereInput;
};

export type ErrorsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type ErrorsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  errorName?: Prisma.SortOrder;
  errorDesc?: Prisma.SortOrder;
  errorPriority?: Prisma.SortOrder;
  errorDateAndTime?: Prisma.SortOrder;
  errorResolveDateAndTime?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
};

export type ErrorsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
};

export type ErrorsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  errorName?: Prisma.SortOrder;
  errorDesc?: Prisma.SortOrder;
  errorPriority?: Prisma.SortOrder;
  errorDateAndTime?: Prisma.SortOrder;
  errorResolveDateAndTime?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
};

export type ErrorsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  errorName?: Prisma.SortOrder;
  errorDesc?: Prisma.SortOrder;
  errorPriority?: Prisma.SortOrder;
  errorDateAndTime?: Prisma.SortOrder;
  errorResolveDateAndTime?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
};

export type ErrorsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  userId?: Prisma.SortOrder;
};

export type ErrorsCreateNestedManyWithoutUserInput = {
  create?:
    | Prisma.XOR<Prisma.ErrorsCreateWithoutUserInput, Prisma.ErrorsUncheckedCreateWithoutUserInput>
    | Prisma.ErrorsCreateWithoutUserInput[]
    | Prisma.ErrorsUncheckedCreateWithoutUserInput[];
  connectOrCreate?: Prisma.ErrorsCreateOrConnectWithoutUserInput | Prisma.ErrorsCreateOrConnectWithoutUserInput[];
  createMany?: Prisma.ErrorsCreateManyUserInputEnvelope;
  connect?: Prisma.ErrorsWhereUniqueInput | Prisma.ErrorsWhereUniqueInput[];
};

export type ErrorsUncheckedCreateNestedManyWithoutUserInput = {
  create?:
    | Prisma.XOR<Prisma.ErrorsCreateWithoutUserInput, Prisma.ErrorsUncheckedCreateWithoutUserInput>
    | Prisma.ErrorsCreateWithoutUserInput[]
    | Prisma.ErrorsUncheckedCreateWithoutUserInput[];
  connectOrCreate?: Prisma.ErrorsCreateOrConnectWithoutUserInput | Prisma.ErrorsCreateOrConnectWithoutUserInput[];
  createMany?: Prisma.ErrorsCreateManyUserInputEnvelope;
  connect?: Prisma.ErrorsWhereUniqueInput | Prisma.ErrorsWhereUniqueInput[];
};

export type ErrorsUpdateManyWithoutUserNestedInput = {
  create?:
    | Prisma.XOR<Prisma.ErrorsCreateWithoutUserInput, Prisma.ErrorsUncheckedCreateWithoutUserInput>
    | Prisma.ErrorsCreateWithoutUserInput[]
    | Prisma.ErrorsUncheckedCreateWithoutUserInput[];
  connectOrCreate?: Prisma.ErrorsCreateOrConnectWithoutUserInput | Prisma.ErrorsCreateOrConnectWithoutUserInput[];
  upsert?: Prisma.ErrorsUpsertWithWhereUniqueWithoutUserInput | Prisma.ErrorsUpsertWithWhereUniqueWithoutUserInput[];
  createMany?: Prisma.ErrorsCreateManyUserInputEnvelope;
  set?: Prisma.ErrorsWhereUniqueInput | Prisma.ErrorsWhereUniqueInput[];
  disconnect?: Prisma.ErrorsWhereUniqueInput | Prisma.ErrorsWhereUniqueInput[];
  delete?: Prisma.ErrorsWhereUniqueInput | Prisma.ErrorsWhereUniqueInput[];
  connect?: Prisma.ErrorsWhereUniqueInput | Prisma.ErrorsWhereUniqueInput[];
  update?: Prisma.ErrorsUpdateWithWhereUniqueWithoutUserInput | Prisma.ErrorsUpdateWithWhereUniqueWithoutUserInput[];
  updateMany?: Prisma.ErrorsUpdateManyWithWhereWithoutUserInput | Prisma.ErrorsUpdateManyWithWhereWithoutUserInput[];
  deleteMany?: Prisma.ErrorsScalarWhereInput | Prisma.ErrorsScalarWhereInput[];
};

export type ErrorsUncheckedUpdateManyWithoutUserNestedInput = {
  create?:
    | Prisma.XOR<Prisma.ErrorsCreateWithoutUserInput, Prisma.ErrorsUncheckedCreateWithoutUserInput>
    | Prisma.ErrorsCreateWithoutUserInput[]
    | Prisma.ErrorsUncheckedCreateWithoutUserInput[];
  connectOrCreate?: Prisma.ErrorsCreateOrConnectWithoutUserInput | Prisma.ErrorsCreateOrConnectWithoutUserInput[];
  upsert?: Prisma.ErrorsUpsertWithWhereUniqueWithoutUserInput | Prisma.ErrorsUpsertWithWhereUniqueWithoutUserInput[];
  createMany?: Prisma.ErrorsCreateManyUserInputEnvelope;
  set?: Prisma.ErrorsWhereUniqueInput | Prisma.ErrorsWhereUniqueInput[];
  disconnect?: Prisma.ErrorsWhereUniqueInput | Prisma.ErrorsWhereUniqueInput[];
  delete?: Prisma.ErrorsWhereUniqueInput | Prisma.ErrorsWhereUniqueInput[];
  connect?: Prisma.ErrorsWhereUniqueInput | Prisma.ErrorsWhereUniqueInput[];
  update?: Prisma.ErrorsUpdateWithWhereUniqueWithoutUserInput | Prisma.ErrorsUpdateWithWhereUniqueWithoutUserInput[];
  updateMany?: Prisma.ErrorsUpdateManyWithWhereWithoutUserInput | Prisma.ErrorsUpdateManyWithWhereWithoutUserInput[];
  deleteMany?: Prisma.ErrorsScalarWhereInput | Prisma.ErrorsScalarWhereInput[];
};

export type NullableEnumErrorPriorityFieldUpdateOperationsInput = {
  set?: $Enums.ErrorPriority | null;
};

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null;
};

export type ErrorsCreateWithoutUserInput = {
  errorName: string;
  errorDesc: string;
  errorPriority?: $Enums.ErrorPriority | null;
  errorDateAndTime?: Date | string;
  errorResolveDateAndTime?: Date | string | null;
};

export type ErrorsUncheckedCreateWithoutUserInput = {
  id?: number;
  errorName: string;
  errorDesc: string;
  errorPriority?: $Enums.ErrorPriority | null;
  errorDateAndTime?: Date | string;
  errorResolveDateAndTime?: Date | string | null;
};

export type ErrorsCreateOrConnectWithoutUserInput = {
  where: Prisma.ErrorsWhereUniqueInput;
  create: Prisma.XOR<Prisma.ErrorsCreateWithoutUserInput, Prisma.ErrorsUncheckedCreateWithoutUserInput>;
};

export type ErrorsCreateManyUserInputEnvelope = {
  data: Prisma.ErrorsCreateManyUserInput | Prisma.ErrorsCreateManyUserInput[];
  skipDuplicates?: boolean;
};

export type ErrorsUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ErrorsWhereUniqueInput;
  update: Prisma.XOR<Prisma.ErrorsUpdateWithoutUserInput, Prisma.ErrorsUncheckedUpdateWithoutUserInput>;
  create: Prisma.XOR<Prisma.ErrorsCreateWithoutUserInput, Prisma.ErrorsUncheckedCreateWithoutUserInput>;
};

export type ErrorsUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ErrorsWhereUniqueInput;
  data: Prisma.XOR<Prisma.ErrorsUpdateWithoutUserInput, Prisma.ErrorsUncheckedUpdateWithoutUserInput>;
};

export type ErrorsUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ErrorsScalarWhereInput;
  data: Prisma.XOR<Prisma.ErrorsUpdateManyMutationInput, Prisma.ErrorsUncheckedUpdateManyWithoutUserInput>;
};

export type ErrorsScalarWhereInput = {
  AND?: Prisma.ErrorsScalarWhereInput | Prisma.ErrorsScalarWhereInput[];
  OR?: Prisma.ErrorsScalarWhereInput[];
  NOT?: Prisma.ErrorsScalarWhereInput | Prisma.ErrorsScalarWhereInput[];
  id?: Prisma.IntFilter<'Errors'> | number;
  errorName?: Prisma.StringFilter<'Errors'> | string;
  errorDesc?: Prisma.StringFilter<'Errors'> | string;
  errorPriority?: Prisma.EnumErrorPriorityNullableFilter<'Errors'> | $Enums.ErrorPriority | null;
  errorDateAndTime?: Prisma.DateTimeFilter<'Errors'> | Date | string;
  errorResolveDateAndTime?: Prisma.DateTimeNullableFilter<'Errors'> | Date | string | null;
  userId?: Prisma.IntFilter<'Errors'> | number;
};

export type ErrorsCreateManyUserInput = {
  id?: number;
  errorName: string;
  errorDesc: string;
  errorPriority?: $Enums.ErrorPriority | null;
  errorDateAndTime?: Date | string;
  errorResolveDateAndTime?: Date | string | null;
};

export type ErrorsUpdateWithoutUserInput = {
  errorName?: Prisma.StringFieldUpdateOperationsInput | string;
  errorDesc?: Prisma.StringFieldUpdateOperationsInput | string;
  errorPriority?: Prisma.NullableEnumErrorPriorityFieldUpdateOperationsInput | $Enums.ErrorPriority | null;
  errorDateAndTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  errorResolveDateAndTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
};

export type ErrorsUncheckedUpdateWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number;
  errorName?: Prisma.StringFieldUpdateOperationsInput | string;
  errorDesc?: Prisma.StringFieldUpdateOperationsInput | string;
  errorPriority?: Prisma.NullableEnumErrorPriorityFieldUpdateOperationsInput | $Enums.ErrorPriority | null;
  errorDateAndTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  errorResolveDateAndTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
};

export type ErrorsUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number;
  errorName?: Prisma.StringFieldUpdateOperationsInput | string;
  errorDesc?: Prisma.StringFieldUpdateOperationsInput | string;
  errorPriority?: Prisma.NullableEnumErrorPriorityFieldUpdateOperationsInput | $Enums.ErrorPriority | null;
  errorDateAndTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  errorResolveDateAndTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null;
};

export type ErrorsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  runtime.Types.Extensions.GetSelect<
    {
      id?: boolean;
      errorName?: boolean;
      errorDesc?: boolean;
      errorPriority?: boolean;
      errorDateAndTime?: boolean;
      errorResolveDateAndTime?: boolean;
      userId?: boolean;
      user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
    },
    ExtArgs['result']['errors']
  >;

export type ErrorsSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    errorName?: boolean;
    errorDesc?: boolean;
    errorPriority?: boolean;
    errorDateAndTime?: boolean;
    errorResolveDateAndTime?: boolean;
    userId?: boolean;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['errors']
>;

export type ErrorsSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    errorName?: boolean;
    errorDesc?: boolean;
    errorPriority?: boolean;
    errorDateAndTime?: boolean;
    errorResolveDateAndTime?: boolean;
    userId?: boolean;
    user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['errors']
>;

export type ErrorsSelectScalar = {
  id?: boolean;
  errorName?: boolean;
  errorDesc?: boolean;
  errorPriority?: boolean;
  errorDateAndTime?: boolean;
  errorResolveDateAndTime?: boolean;
  userId?: boolean;
};

export type ErrorsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  runtime.Types.Extensions.GetOmit<
    'id' | 'errorName' | 'errorDesc' | 'errorPriority' | 'errorDateAndTime' | 'errorResolveDateAndTime' | 'userId',
    ExtArgs['result']['errors']
  >;
export type ErrorsInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};
export type ErrorsIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};
export type ErrorsIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>;
};

export type $ErrorsPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'Errors';
  objects: {
    user: Prisma.$UserPayload<ExtArgs>;
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: number;
      errorName: string;
      errorDesc: string;
      errorPriority: $Enums.ErrorPriority | null;
      errorDateAndTime: Date;
      errorResolveDateAndTime: Date | null;
      userId: number;
    },
    ExtArgs['result']['errors']
  >;
  composites: {};
};

export type ErrorsGetPayload<S extends boolean | null | undefined | ErrorsDefaultArgs> = runtime.Types.Result.GetResult<
  Prisma.$ErrorsPayload,
  S
>;

export type ErrorsCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<ErrorsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: ErrorsCountAggregateInputType | true;
};

export interface ErrorsDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['Errors'];
    meta: { name: 'Errors' };
  };
  /**
   * Find zero or one Errors that matches the filter.
   * @param {ErrorsFindUniqueArgs} args - Arguments to find a Errors
   * @example
   * // Get one Errors
   * const errors = await prisma.errors.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ErrorsFindUniqueArgs>(
    args: Prisma.SelectSubset<T, ErrorsFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__ErrorsClient<
    runtime.Types.Result.GetResult<Prisma.$ErrorsPayload<ExtArgs>, T, 'findUnique', GlobalOmitOptions> | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one Errors that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ErrorsFindUniqueOrThrowArgs} args - Arguments to find a Errors
   * @example
   * // Get one Errors
   * const errors = await prisma.errors.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ErrorsFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, ErrorsFindUniqueOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__ErrorsClient<
    runtime.Types.Result.GetResult<Prisma.$ErrorsPayload<ExtArgs>, T, 'findUniqueOrThrow', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first Errors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ErrorsFindFirstArgs} args - Arguments to find a Errors
   * @example
   * // Get one Errors
   * const errors = await prisma.errors.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ErrorsFindFirstArgs>(
    args?: Prisma.SelectSubset<T, ErrorsFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__ErrorsClient<
    runtime.Types.Result.GetResult<Prisma.$ErrorsPayload<ExtArgs>, T, 'findFirst', GlobalOmitOptions> | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first Errors that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ErrorsFindFirstOrThrowArgs} args - Arguments to find a Errors
   * @example
   * // Get one Errors
   * const errors = await prisma.errors.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ErrorsFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, ErrorsFindFirstOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__ErrorsClient<
    runtime.Types.Result.GetResult<Prisma.$ErrorsPayload<ExtArgs>, T, 'findFirstOrThrow', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more Errors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ErrorsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Errors
   * const errors = await prisma.errors.findMany()
   *
   * // Get first 10 Errors
   * const errors = await prisma.errors.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const errorsWithIdOnly = await prisma.errors.findMany({ select: { id: true } })
   *
   */
  findMany<T extends ErrorsFindManyArgs>(
    args?: Prisma.SelectSubset<T, ErrorsFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<Prisma.$ErrorsPayload<ExtArgs>, T, 'findMany', GlobalOmitOptions>
  >;

  /**
   * Create a Errors.
   * @param {ErrorsCreateArgs} args - Arguments to create a Errors.
   * @example
   * // Create one Errors
   * const Errors = await prisma.errors.create({
   *   data: {
   *     // ... data to create a Errors
   *   }
   * })
   *
   */
  create<T extends ErrorsCreateArgs>(
    args: Prisma.SelectSubset<T, ErrorsCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__ErrorsClient<
    runtime.Types.Result.GetResult<Prisma.$ErrorsPayload<ExtArgs>, T, 'create', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many Errors.
   * @param {ErrorsCreateManyArgs} args - Arguments to create many Errors.
   * @example
   * // Create many Errors
   * const errors = await prisma.errors.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends ErrorsCreateManyArgs>(
    args?: Prisma.SelectSubset<T, ErrorsCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many Errors and returns the data saved in the database.
   * @param {ErrorsCreateManyAndReturnArgs} args - Arguments to create many Errors.
   * @example
   * // Create many Errors
   * const errors = await prisma.errors.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many Errors and only return the `id`
   * const errorsWithIdOnly = await prisma.errors.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends ErrorsCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, ErrorsCreateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<Prisma.$ErrorsPayload<ExtArgs>, T, 'createManyAndReturn', GlobalOmitOptions>
  >;

  /**
   * Delete a Errors.
   * @param {ErrorsDeleteArgs} args - Arguments to delete one Errors.
   * @example
   * // Delete one Errors
   * const Errors = await prisma.errors.delete({
   *   where: {
   *     // ... filter to delete one Errors
   *   }
   * })
   *
   */
  delete<T extends ErrorsDeleteArgs>(
    args: Prisma.SelectSubset<T, ErrorsDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__ErrorsClient<
    runtime.Types.Result.GetResult<Prisma.$ErrorsPayload<ExtArgs>, T, 'delete', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one Errors.
   * @param {ErrorsUpdateArgs} args - Arguments to update one Errors.
   * @example
   * // Update one Errors
   * const errors = await prisma.errors.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends ErrorsUpdateArgs>(
    args: Prisma.SelectSubset<T, ErrorsUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__ErrorsClient<
    runtime.Types.Result.GetResult<Prisma.$ErrorsPayload<ExtArgs>, T, 'update', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more Errors.
   * @param {ErrorsDeleteManyArgs} args - Arguments to filter Errors to delete.
   * @example
   * // Delete a few Errors
   * const { count } = await prisma.errors.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends ErrorsDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, ErrorsDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more Errors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ErrorsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Errors
   * const errors = await prisma.errors.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends ErrorsUpdateManyArgs>(
    args: Prisma.SelectSubset<T, ErrorsUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more Errors and returns the data updated in the database.
   * @param {ErrorsUpdateManyAndReturnArgs} args - Arguments to update many Errors.
   * @example
   * // Update many Errors
   * const errors = await prisma.errors.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more Errors and only return the `id`
   * const errorsWithIdOnly = await prisma.errors.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends ErrorsUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, ErrorsUpdateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<Prisma.$ErrorsPayload<ExtArgs>, T, 'updateManyAndReturn', GlobalOmitOptions>
  >;

  /**
   * Create or update one Errors.
   * @param {ErrorsUpsertArgs} args - Arguments to update or create a Errors.
   * @example
   * // Update or create a Errors
   * const errors = await prisma.errors.upsert({
   *   create: {
   *     // ... data to create a Errors
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Errors we want to update
   *   }
   * })
   */
  upsert<T extends ErrorsUpsertArgs>(
    args: Prisma.SelectSubset<T, ErrorsUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__ErrorsClient<
    runtime.Types.Result.GetResult<Prisma.$ErrorsPayload<ExtArgs>, T, 'upsert', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of Errors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ErrorsCountArgs} args - Arguments to filter Errors to count.
   * @example
   * // Count the number of Errors
   * const count = await prisma.errors.count({
   *   where: {
   *     // ... the filter for the Errors we want to count
   *   }
   * })
   **/
  count<T extends ErrorsCountArgs>(
    args?: Prisma.Subset<T, ErrorsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ErrorsCountAggregateOutputType>
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a Errors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ErrorsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends ErrorsAggregateArgs>(
    args: Prisma.Subset<T, ErrorsAggregateArgs>,
  ): Prisma.PrismaPromise<GetErrorsAggregateType<T>>;

  /**
   * Group by Errors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ErrorsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends ErrorsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<T>>, Prisma.Extends<'take', Prisma.Keys<T>>>,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ErrorsGroupByArgs['orderBy'] }
      : { orderBy?: ErrorsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`];
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, ErrorsGroupByArgs, OrderByArg> & InputErrors,
  ): {} extends InputErrors ? GetErrorsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the Errors model
   */
  readonly fields: ErrorsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Errors.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ErrorsClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise';
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__UserClient<
    runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, 'findUniqueOrThrow', GlobalOmitOptions> | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the Errors model
 */
export interface ErrorsFieldRefs {
  readonly id: Prisma.FieldRef<'Errors', 'Int'>;
  readonly errorName: Prisma.FieldRef<'Errors', 'String'>;
  readonly errorDesc: Prisma.FieldRef<'Errors', 'String'>;
  readonly errorPriority: Prisma.FieldRef<'Errors', 'ErrorPriority'>;
  readonly errorDateAndTime: Prisma.FieldRef<'Errors', 'DateTime'>;
  readonly errorResolveDateAndTime: Prisma.FieldRef<'Errors', 'DateTime'>;
  readonly userId: Prisma.FieldRef<'Errors', 'Int'>;
}

// Custom InputTypes
/**
 * Errors findUnique
 */
export type ErrorsFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Errors
   */
  select?: Prisma.ErrorsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Errors
   */
  omit?: Prisma.ErrorsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ErrorsInclude<ExtArgs> | null;
  /**
   * Filter, which Errors to fetch.
   */
  where: Prisma.ErrorsWhereUniqueInput;
};

/**
 * Errors findUniqueOrThrow
 */
export type ErrorsFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Errors
   */
  select?: Prisma.ErrorsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Errors
   */
  omit?: Prisma.ErrorsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ErrorsInclude<ExtArgs> | null;
  /**
   * Filter, which Errors to fetch.
   */
  where: Prisma.ErrorsWhereUniqueInput;
};

/**
 * Errors findFirst
 */
export type ErrorsFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Errors
   */
  select?: Prisma.ErrorsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Errors
   */
  omit?: Prisma.ErrorsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ErrorsInclude<ExtArgs> | null;
  /**
   * Filter, which Errors to fetch.
   */
  where?: Prisma.ErrorsWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Errors to fetch.
   */
  orderBy?: Prisma.ErrorsOrderByWithRelationInput | Prisma.ErrorsOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for Errors.
   */
  cursor?: Prisma.ErrorsWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Errors from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Errors.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of Errors.
   */
  distinct?: Prisma.ErrorsScalarFieldEnum | Prisma.ErrorsScalarFieldEnum[];
};

/**
 * Errors findFirstOrThrow
 */
export type ErrorsFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Errors
   */
  select?: Prisma.ErrorsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Errors
   */
  omit?: Prisma.ErrorsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ErrorsInclude<ExtArgs> | null;
  /**
   * Filter, which Errors to fetch.
   */
  where?: Prisma.ErrorsWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Errors to fetch.
   */
  orderBy?: Prisma.ErrorsOrderByWithRelationInput | Prisma.ErrorsOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for Errors.
   */
  cursor?: Prisma.ErrorsWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Errors from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Errors.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of Errors.
   */
  distinct?: Prisma.ErrorsScalarFieldEnum | Prisma.ErrorsScalarFieldEnum[];
};

/**
 * Errors findMany
 */
export type ErrorsFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Errors
   */
  select?: Prisma.ErrorsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Errors
   */
  omit?: Prisma.ErrorsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ErrorsInclude<ExtArgs> | null;
  /**
   * Filter, which Errors to fetch.
   */
  where?: Prisma.ErrorsWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Errors to fetch.
   */
  orderBy?: Prisma.ErrorsOrderByWithRelationInput | Prisma.ErrorsOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing Errors.
   */
  cursor?: Prisma.ErrorsWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Errors from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Errors.
   */
  skip?: number;
  distinct?: Prisma.ErrorsScalarFieldEnum | Prisma.ErrorsScalarFieldEnum[];
};

/**
 * Errors create
 */
export type ErrorsCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Errors
   */
  select?: Prisma.ErrorsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Errors
   */
  omit?: Prisma.ErrorsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ErrorsInclude<ExtArgs> | null;
  /**
   * The data needed to create a Errors.
   */
  data: Prisma.XOR<Prisma.ErrorsCreateInput, Prisma.ErrorsUncheckedCreateInput>;
};

/**
 * Errors createMany
 */
export type ErrorsCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many Errors.
   */
  data: Prisma.ErrorsCreateManyInput | Prisma.ErrorsCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * Errors createManyAndReturn
 */
export type ErrorsCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Errors
   */
  select?: Prisma.ErrorsSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the Errors
   */
  omit?: Prisma.ErrorsOmit<ExtArgs> | null;
  /**
   * The data used to create many Errors.
   */
  data: Prisma.ErrorsCreateManyInput | Prisma.ErrorsCreateManyInput[];
  skipDuplicates?: boolean;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ErrorsIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * Errors update
 */
export type ErrorsUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Errors
   */
  select?: Prisma.ErrorsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Errors
   */
  omit?: Prisma.ErrorsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ErrorsInclude<ExtArgs> | null;
  /**
   * The data needed to update a Errors.
   */
  data: Prisma.XOR<Prisma.ErrorsUpdateInput, Prisma.ErrorsUncheckedUpdateInput>;
  /**
   * Choose, which Errors to update.
   */
  where: Prisma.ErrorsWhereUniqueInput;
};

/**
 * Errors updateMany
 */
export type ErrorsUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update Errors.
   */
  data: Prisma.XOR<Prisma.ErrorsUpdateManyMutationInput, Prisma.ErrorsUncheckedUpdateManyInput>;
  /**
   * Filter which Errors to update
   */
  where?: Prisma.ErrorsWhereInput;
  /**
   * Limit how many Errors to update.
   */
  limit?: number;
};

/**
 * Errors updateManyAndReturn
 */
export type ErrorsUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Errors
   */
  select?: Prisma.ErrorsSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the Errors
   */
  omit?: Prisma.ErrorsOmit<ExtArgs> | null;
  /**
   * The data used to update Errors.
   */
  data: Prisma.XOR<Prisma.ErrorsUpdateManyMutationInput, Prisma.ErrorsUncheckedUpdateManyInput>;
  /**
   * Filter which Errors to update
   */
  where?: Prisma.ErrorsWhereInput;
  /**
   * Limit how many Errors to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ErrorsIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * Errors upsert
 */
export type ErrorsUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Errors
   */
  select?: Prisma.ErrorsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Errors
   */
  omit?: Prisma.ErrorsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ErrorsInclude<ExtArgs> | null;
  /**
   * The filter to search for the Errors to update in case it exists.
   */
  where: Prisma.ErrorsWhereUniqueInput;
  /**
   * In case the Errors found by the `where` argument doesn't exist, create a new Errors with this data.
   */
  create: Prisma.XOR<Prisma.ErrorsCreateInput, Prisma.ErrorsUncheckedCreateInput>;
  /**
   * In case the Errors was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ErrorsUpdateInput, Prisma.ErrorsUncheckedUpdateInput>;
};

/**
 * Errors delete
 */
export type ErrorsDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Errors
   */
  select?: Prisma.ErrorsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Errors
   */
  omit?: Prisma.ErrorsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ErrorsInclude<ExtArgs> | null;
  /**
   * Filter which Errors to delete.
   */
  where: Prisma.ErrorsWhereUniqueInput;
};

/**
 * Errors deleteMany
 */
export type ErrorsDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which Errors to delete
   */
  where?: Prisma.ErrorsWhereInput;
  /**
   * Limit how many Errors to delete.
   */
  limit?: number;
};

/**
 * Errors without action
 */
export type ErrorsDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Errors
   */
  select?: Prisma.ErrorsSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the Errors
   */
  omit?: Prisma.ErrorsOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ErrorsInclude<ExtArgs> | null;
};
